## To implement
repos:
  - repo: local
    hooks: 
      - id: unit-test
        name: Running unit tests
        entry: pipenv run test
        language: system
        types: [python]
        pass_filenames: false 
      - id: formatting
        name: Formatting the code
        entry: pipenv run format
        language: system
        types: [python]
      - id: linting
        name: Linting the code
        entry: pipenv run lint
        language: system
        types: [python]
      - id: typecheck
        name: Typechecking the code
        entry: pipenv run typecheck
        pass_filenames: false
        language: system
        types: [python]