## To implement
repos:
  - repo: local
    hooks: 
      - id: unit-test
        name: Run unit tests
        entry: pipenv run test
        language: system
        types: [python]
      - id: linting
        name: Linting the code
        entry: pipenv run lint
        language: system
        types: [python]
      - id: formatting
        name: Formatting the code
        entry: pipenv run format
        language: system
        types: [python]
      - id: typecheck
        name: Typechecks the code
        entry: pipenv run typecheck
        language: system
        types: [python]