version: '3.8'
services:
  oxygencs-grp1-eq10:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    environment:
      - PYTHONUNBUFFERED=1
    command:
      - pipenv
      - run
      - start
