name: Test du code

on:
  push:
    branches: [ "16-mettre-en-place-le-workflow-github" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pipenv install
        pipenv install
    - name: Lint with pylint
      run: pipenv run pytest